name: 'Build & Deploy GH Pages'

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous
        uses: styfle/cancel-workflow-action@0.11.0
        with:
            access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 18.16.0
      - name: npm install
        run: |
              git config --global user.email "azam@rapidsilicon.com"
              git config --global user.name $GITHUB_ACTOR
              #export GIT_USER=$GITHUB_ACTOR
              echo $GIT_USER
              npm install
              yarn deploy
        env:
              GIT_USER: ${{ github.actor }}:${{ secrets.RGPT }}
      - name: move build/* to doc
        run: |
              cp -rf build/* docs
              ls -l docs
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
